// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIRG.Persistences.Context;

#nullable disable

namespace SIRG.Persistences.Migrations
{
    [DbContext(typeof(SIRGContext))]
    partial class SIRGContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIRG.Domain.Entities.Categories", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Customers", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.DishIngredients", b =>
                {
                    b.Property<int>("DishIngredientsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishIngredientsId"));

                    b.Property<int>("DishID")
                        .HasColumnType("int");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientsIngredientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("QuantityRequired")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DishIngredientsId");

                    b.HasIndex("DishID");

                    b.HasIndex("IngredientsIngredientId");

                    b.ToTable("DishIngredients");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Dishes", b =>
                {
                    b.Property<int>("DishID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishID"));

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryID1")
                        .HasColumnType("int");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DishID");

                    b.HasIndex("CategoryID1");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Ingredients", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinimunStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryID"));

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.HasKey("InventoryID");

                    b.HasIndex("IngredientID");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.InventoryMovements", b =>
                {
                    b.Property<int>("MovementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementID"));

                    b.Property<int>("IngredientID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovementID");

                    b.HasIndex("IngredientID");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailsID"));

                    b.Property<int>("DishID")
                        .HasColumnType("int");

                    b.Property<int?>("DishesDishID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int?>("OrdersOrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailsID");

                    b.HasIndex("DishesDishID");

                    b.HasIndex("OrdersOrderID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Orders", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderStatusStatusID")
                        .HasColumnType("int");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationsReservationID")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("WaiterID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("OrderStatusStatusID");

                    b.HasIndex("ReservationsReservationID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.ReservationStatus", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("ReservationStatus");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Reservations", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomersCustomerID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReservationDate")
                        .HasColumnType("date");

                    b.Property<int?>("ReservationStatusStatusID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ReservationTime")
                        .HasColumnType("time");

                    b.Property<int?>("RestaurantTablesTableID")
                        .HasColumnType("int");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<int>("TableID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("CustomersCustomerID");

                    b.HasIndex("ReservationStatusStatusID");

                    b.HasIndex("RestaurantTablesTableID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.RestaurantTables", b =>
                {
                    b.Property<int>("TableID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("TableID");

                    b.ToTable("RestaurantTables");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.SaleDetails", b =>
                {
                    b.Property<int>("SaleDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleDetailsID"));

                    b.Property<int>("DishID")
                        .HasColumnType("int");

                    b.Property<int?>("DishesDishID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleID")
                        .HasColumnType("int");

                    b.Property<int?>("SalesSaleID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleDetailsID");

                    b.HasIndex("DishesDishID");

                    b.HasIndex("SalesSaleID");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Sales", b =>
                {
                    b.Property<int>("SaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleID");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.DishIngredients", b =>
                {
                    b.HasOne("SIRG.Domain.Entities.Dishes", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIRG.Domain.Entities.Ingredients", "Ingredients")
                        .WithMany("DishIngredients")
                        .HasForeignKey("IngredientsIngredientId");

                    b.Navigation("Dish");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Dishes", b =>
                {
                    b.HasOne("SIRG.Domain.Entities.Categories", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryID1");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("SIRG.Domain.Entities.Ingredients", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.InventoryMovements", b =>
                {
                    b.HasOne("SIRG.Domain.Entities.Ingredients", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.OrderDetails", b =>
                {
                    b.HasOne("SIRG.Domain.Entities.Dishes", "Dishes")
                        .WithMany("OrderDetails")
                        .HasForeignKey("DishesDishID");

                    b.HasOne("SIRG.Domain.Entities.Orders", "Orders")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrdersOrderID");

                    b.Navigation("Dishes");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Orders", b =>
                {
                    b.HasOne("SIRG.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusStatusID");

                    b.HasOne("SIRG.Domain.Entities.Reservations", "Reservations")
                        .WithMany("Orders")
                        .HasForeignKey("ReservationsReservationID");

                    b.Navigation("OrderStatus");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Reservations", b =>
                {
                    b.HasOne("SIRG.Domain.Entities.Customers", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomersCustomerID");

                    b.HasOne("SIRG.Domain.Entities.ReservationStatus", "ReservationStatus")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationStatusStatusID");

                    b.HasOne("SIRG.Domain.Entities.RestaurantTables", "RestaurantTables")
                        .WithMany("Reservations")
                        .HasForeignKey("RestaurantTablesTableID");

                    b.Navigation("Customers");

                    b.Navigation("ReservationStatus");

                    b.Navigation("RestaurantTables");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.SaleDetails", b =>
                {
                    b.HasOne("SIRG.Domain.Entities.Dishes", "Dishes")
                        .WithMany("SaleDetails")
                        .HasForeignKey("DishesDishID");

                    b.HasOne("SIRG.Domain.Entities.Sales", "Sales")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SalesSaleID");

                    b.Navigation("Dishes");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Categories", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Dishes", b =>
                {
                    b.Navigation("DishIngredients");

                    b.Navigation("OrderDetails");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Ingredients", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Orders", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.ReservationStatus", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Reservations", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.RestaurantTables", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SIRG.Domain.Entities.Sales", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
